ultrasonic_node:
  ros__parameters:
    raw_topic: "/arduino/ultrasonic_raw"
    sensor_names: ["1", "2", "3", "4", "5", "6"]
    frame_prefix: "ultrasonic_"
    field_of_view: 0.26
    min_range: 0.02
    max_range: 4.0
